import type * as CSS from 'csstype';

export const shorthands: Partial<Record<keyof CSS.StandardShorthandProperties, [number, string[]]>> = {
  animation: [
    -1,
    [
      'animationName',
      'animationDuration',
      'animationTimingFunction',
      'animationDelay',
      'animationDirection',
      'animationIterationCount',
      'animationFillMode',
      'animationPlayState',
      'animationTimeline',
    ],
  ],
  animationRange: [-1, ['animationRangeStart', 'animationRangeEnd']],
  background: [
    -2,
    [
      'backgroundImage',
      'backgroundPosition',
      'backgroundSize',
      'backgroundRepeat',
      'backgroundOrigin',
      'backgroundClip',
      'backgroundAttachment',
      'backgroundColor',
    ],
  ],
  backgroundPosition: [-1, ['backgroundPositionX', 'backgroundPositionY']],
  border: [
    -2,
    [
      'borderWidth',
      'borderStyle',
      'borderColor',

      'borderLeft',
      'borderRight',
      'borderTop',
      'borderBottom',

      'borderLeftWidth',
      'borderRightWidth',
      'borderTopWidth',
      'borderBottomWidth',

      'borderLeftStyle',
      'borderRightStyle',
      'borderTopStyle',
      'borderBottomStyle',

      'borderLeftColor',
      'borderRightColor',
      'borderTopColor',
      'borderBottomColor',
    ],
  ],
  borderBlock: [-1, ['borderBlockWidth', 'borderBlockStyle', 'borderBlockColor']],
  borderBlockEnd: [-1, ['borderTopWidth', 'borderTopStyle', 'borderTopColor']],
  borderBlockStart: [-2, ['borderWidth', 'borderStyle', 'borderBlockStartColor']],
  borderBottom: [-1, ['borderBottomWidth', 'borderBottomStyle', 'borderBottomColor']],
  borderColor: [-1, ['borderBottomColor', 'borderLeftColor', 'borderRightColor', 'borderTopColor']],
  borderImage: [
    -1,
    ['borderImageOutset', 'borderImageRepeat', 'borderImageSlice', 'borderImageSource', 'borderImageWidth'],
  ],
  borderInline: [-1, ['borderInlineWidth', 'borderInlineStyle', 'borderInlineColor']],
  borderInlineEnd: [-2, ['borderWidth', 'borderStyle', 'borderInlineEndColor']],
  borderInlineStart: [-2, ['borderWidth', 'borderStyle', 'borderInlineStartColor']],
  borderLeft: [-1, ['borderLeftWidth', 'borderLeftStyle', 'borderLeftColor']],
  borderRadius: [
    -1,
    ['borderBottomLeftRadius', 'borderBottomRightRadius', 'borderTopLeftRadius', 'borderTopRightRadius'],
  ],
  borderRight: [-1, ['borderRightWidth', 'borderRightStyle', 'borderRightColor']],
  borderStyle: [-1, ['borderBottomStyle', 'borderLeftStyle', 'borderRightStyle', 'borderTopStyle']],
  borderTop: [-1, ['borderTopWidth', 'borderTopStyle', 'borderTopColor']],
  borderWidth: [-1, ['borderBottomWidth', 'borderLeftWidth', 'borderRightWidth', 'borderTopWidth']],
  caret: [-1, ['caretColor', 'caretShape']],
  columnRule: [-1, ['columnRuleColor', 'columnRuleStyle', 'columnRuleWidth']],
  columns: [-1, ['columnWidth', 'columnCount']],
  containIntrinsicSize: [-1, ['containIntrinsicWidth', 'containIntrinsicHeight']],
  container: [-1, ['containerName', 'containerType']],
  flex: [-1, ['flexGrow', 'flexShrink', 'flexBasis']],
  flexFlow: [-1, ['flexDirection', 'flexWrap']],
  font: [-1, ['fontStyle', 'fontVariant', 'fontWeight', 'fontStretch', 'fontSize', 'lineHeight', 'fontFamily']],
  gap: [-1, ['rowGap', 'columnGap']],
  grid: [
    -1,
    [
      'gridTemplateRows',
      'gridTemplateColumns',
      'gridTemplateAreas',
      'gridAutoRows',
      'gridAutoColumns',
      'gridAutoFlow',
      'gridColumnGap',
      'gridRowGap',
      'columnGap',
      'rowGap',
    ],
  ],
  gridArea: [-1, ['gridRowStart', 'gridColumnStart', 'gridRowEnd', 'gridColumnEnd']],
  gridColumn: [-1, ['gridColumnStart', 'gridColumnEnd']],
  gridRow: [-1, ['gridRowStart', 'gridRowEnd']],
  gridTemplate: [-1, ['gridTemplateColumns', 'gridTemplateRows', 'gridTemplateAreas']],
  inset: [-1, ['top', 'bottom', 'left', 'right']],
  insetBlock: [-1, ['insetBlockStart', 'insetBlockEnd']],
  insetInline: [-1, ['insetInlineStart', 'insetInlineEnd']],
  listStyle: [-1, ['listStyleImage', 'listStylePosition', 'listStyleType']],
  margin: [-1, ['marginBottom', 'marginLeft', 'marginRight', 'marginTop']],
  marginBlock: [-1, ['marginBlockStart', 'marginBlockEnd']],
  marginInline: [-1, ['marginInlineStart', 'marginInlineEnd']],
  mask: [
    -1,
    ['maskImage', 'maskMode', 'maskRepeat', 'maskPosition', 'maskClip', 'maskOrigin', 'maskSize', 'maskComposite'],
  ],
  maskBorder: [
    -1,
    [
      'maskBorderMode',
      'maskBorderOutset',
      'maskBorderRepeat',
      'maskBorderSlice',
      'maskBorderSource',
      'maskBorderWidth',
    ],
  ],
  offset: [-1, ['offsetPosition', 'offsetPath', 'offsetDistance', 'offsetAnchor', 'offsetRotate']],
  outline: [-1, ['outlineColor', 'outlineWidth', 'outlineStyle']],
  overflow: [-1, ['overflowX', 'overflowY']],
  overscrollBehavior: [-1, ['overscrollBehaviorX', 'overscrollBehaviorY']],
  padding: [-1, ['paddingBottom', 'paddingLeft', 'paddingRight', 'paddingTop']],
  paddingBlock: [-1, ['paddingBlockStart', 'paddingBlockEnd']],
  paddingInline: [-1, ['paddingInlineStart', 'paddingInlineEnd']],
  placeContent: [-1, ['alignContent', 'justifyContent']],
  placeItems: [-1, ['alignItems', 'justifyItems']],
  placeSelf: [-1, ['alignSelf', 'justifySelf']],
  scrollMargin: [-1, ['scrollMarginBottom', 'scrollMarginLeft', 'scrollMarginRight', 'scrollMarginTop']],
  scrollMarginBlock: [-1, ['scrollMarginBlockStart', 'scrollMarginBlockEnd']],
  scrollMarginInline: [-1, ['scrollMarginInlineStart', 'scrollMarginInlineEnd']],
  scrollPadding: [-1, ['scrollPaddingBottom', 'scrollPaddingLeft', 'scrollPaddingRight', 'scrollPaddingTop']],
  scrollPaddingBlock: [-1, ['scrollPaddingBlockStart', 'scrollPaddingBlockEnd']],
  scrollPaddingInline: [-1, ['scrollPaddingInlineStart', 'scrollPaddingInlineEnd']],
  scrollTimeline: [-1, ['scrollTimelineName', 'scrollTimelineAxis']],
  textDecoration: [-1, ['textDecorationLine', 'textDecorationStyle', 'textDecorationColor', 'textDecorationThickness']],
  textEmphasis: [-1, ['textEmphasisStyle', 'textEmphasisColor']],
  transition: [
    -1,
    ['transitionDelay', 'transitionDuration', 'transitionProperty', 'transitionTimingFunction', 'transitionBehavior'],
  ],
  viewTimeline: [-1, ['viewTimelineName', 'viewTimelineAxis']],
};
