const { preserveDirectives } = require('rollup-plugin-preserve-directives');
const fs = require('fs');
const path = require('path');

/**
 * Rollup plugin that removes declaration files (.d.ts, .d.ts.map) generated by
 * @rollup/plugin-typescript. These are incompatible with tsc --build project references
 * (different directory layout), so tsc handles declarations via the type-check target instead.
 */
function cleanDeclarations() {
  return {
    name: 'clean-declarations',
    async writeBundle(outputOptions) {
      const dir = outputOptions.dir;
      if (!dir) return;

      const srcDir = path.join(dir, 'src');
      if (fs.existsSync(srcDir)) {
        fs.rmSync(srcDir, { recursive: true });
      }

      // Remove the barrel index.d.ts and stale .tsbuildinfo generated by rollup
      for (const file of fs.readdirSync(dir)) {
        if (file.endsWith('.d.ts') || file.endsWith('.d.ts.map')) {
          fs.unlinkSync(path.join(dir, file));
        }
      }

      // Remove stale .tsbuildinfo from the package root (rollup's tsc pass creates it)
      const pkgRoot = path.dirname(dir);
      for (const file of fs.readdirSync(pkgRoot)) {
        if (file.endsWith('.tsbuildinfo')) {
          fs.unlinkSync(path.join(pkgRoot, file));
        }
      }
    },
  };
}

function getRollupOptions(/** @type {import('rollup').RollupOptions} */ options) {
  if (Array.isArray(options.output)) {
    options.output = options.output.map(output => ({
      ...output,
      // Stops bundling to a single file and prevents bundle size issues
      preserveModules: true,
      preserveModulesRoot: 'src',
      // Add interop for CJS
      ...(output.format === 'cjs' && { interop: 'compat' }),
    }));

    // Add plugin to preserve 'use client' directives in the output files
    options.plugins = options.plugins || [];
    options.plugins.push(preserveDirectives());
    options.plugins.push(cleanDeclarations());

    return options;
  }

  throw new Error('"options.output" should be an array');
}

module.exports = getRollupOptions;
