// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  reactSidebar: [{ type: 'autogenerated', dirName: 'react' }],
  tryItOutSidebar: [{ type: 'autogenerated', dirName: 'try-it-out' }],
};

module.exports = sidebars;
