name: Bundle size | Comment on PR
on:
  workflow_run:
    workflows: ['Bundle size']
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pull-requests: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: monosize-report
          path: ./results
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load PR number
        id: pr_number
        run: echo "::set-output name=id::$(cat pr.txt)"
        working-directory: ./results

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        with:
          number: ${{ steps.pr_number.outputs.id }}
          path: ./results/monosize.md
