name: Bundle size | Baseline
on:
  push:
    branches:
      - main

env:
  NX_PARALLEL: 4

jobs:
  bundle-size:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' }}

    permissions:
      contents: 'read'
      actions: 'read'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: yarn
          node-version: '24'

      - run: yarn install --immutable

      - name: Measure all packages
        run: yarn nx run-many --all --target=bundle-size --nxBail

      - name: Upload results
        run: yarn monosize upload-report --branch main --commit-sha ${{ github.sha }}
        env:
          UPSTASH_WRITE_TOKEN: ${{ secrets.UPSTASH_WRITE_TOKEN }}
