name: Bundle size | Baseline
on:
  push:
    branches:
      - main

env:
  NX_PARALLEL: 4

jobs:
  bundle-size:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' }}

    permissions:
      contents: 'read'
      actions: 'read'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: yarn
          node-version: '24'

      - run: yarn install --immutable

      - name: Measure all packages
        run: yarn nx run-many --all --target=bundle-size --nxBail

      - name: Upload results
        run: yarn monosize upload-report --branch main --commit-sha ${{ github.sha }}
        env:
          UPSTASH_WRITE_TOKEN: ${{ secrets.UPSTASH_WRITE_TOKEN }}
