name: Changelog
on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' }}

    permissions:
      contents: 'read'
      actions: 'read'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '24'

      - run: npx beachball check --changehint "Run 'yarn change' to generate a change file"
