name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_PARALLEL: 4

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' }}

    permissions:
      contents: 'read'
      actions: 'read'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: 'yarn'
          node-version: '24'

      - run: yarn install --immutable
      - run: yarn dedupe --check
      - run: yarn check-dependencies

      - run: yarn playwright install --with-deps chromium

      - run: yarn nx affected --target=lint,type-check,build,build-cjs,test --nxBail
