# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

env:
  NX_PARALLEL: 4

jobs:
  setup:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all packages
        run: yarn nx run-many --target=build --all