name: GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

env:
  NX_PARALLEL: 4

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' && (contains(github.event.head_commit.message, 'applying package updates') || github.event_name == 'workflow_dispatch') }}

    permissions:
      contents: 'read'
      actions: 'read'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: 'yarn'
          node-version: '24'

      - run: yarn install --immutable
      - run: yarn nx run-many --target=build --projects=@griffel/website --nxBail

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: './dist/apps/website'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
